/**
 * pull-quote — a full-bleed quotation band on the deep-forest ground.
 *
 * Authoring (one row per part):
 *   row 1, cell 1: the quotation
 *   row 2, cell 1: — Attribution
 *
 * Author the quotation as a plain paragraph, NOT a <blockquote>: the runtime's
 * wrapTextNodes folds any cell whose first element is not P/PRE/UL/OL/PICTURE/
 * TABLE/H1-6 into a single <p>, which would swallow the attribution (#104).
 * The block supplies the <blockquote> semantics as a generated WRAPPER around
 * the authored paragraph, so the authored node keeps its identity (EW1).
 *
 * The oversized decorative quotation mark is generated by the block
 * (presentation, not authored content).
 */

/**
 * Collect the authored elements from every cell of the block (#62/#71/#104).
 * @param {Element} block the block element
 * @returns {Element[]} the authored elements in document order
 */
function collectNodes(block) {
  const out = [];
  block.querySelectorAll(':scope > div > div').forEach((cell) => {
    const kids = [...cell.children];
    if (kids.length) out.push(...kids);
    else if (cell.textContent.trim()) {
      // harness-only fallback (EW5)
      const p = document.createElement('p');
      p.append(...cell.childNodes);
      out.push(p);
    }
  });
  return out.length ? out : [...block.children];
}

/**
 * loads and decorates the block
 * @param {Element} block The block element
 */
export default async function decorate(block) {
  const nodes = collectNodes(block);
  if (!nodes.length) return;

  const quote = nodes.find((n) => n.matches('blockquote')) || nodes[0];
  const attribution = nodes.find((n) => n !== quote && n.textContent.trim());

  const inner = document.createElement('div');
  inner.className = 'quote-inner';

  const mark = document.createElement('div');
  mark.className = 'quote-mark';
  mark.setAttribute('aria-hidden', 'true');
  mark.textContent = '"';
  inner.append(mark);

  const body = document.createElement(quote.matches('blockquote') ? 'div' : 'blockquote');
  body.className = 'quote-body';
  body.append(quote);
  inner.append(body);

  if (attribution) {
    const cite = document.createElement('div');
    cite.className = 'quote-attribution';
    cite.append(attribution);
    inner.append(cite);
  }

  block.replaceChildren(inner);
}
