/**
 * closing — the dark closing statement that ends the essay.
 *
 * Authoring (one cell):
 *   <h2>closing statement (use <em> for the accented word)</h2>
 *   <p>closing paragraph</p>
 *   optionally CTA paragraphs (<strong><a> primary, <em><a> secondary)
 *
 * The dot medallion and the closing hairline are generated by the block.
 */

/**
 * Collect the authored elements from every cell of the block (#62/#71/#104).
 * @param {Element} block the block element
 * @returns {Element[]} the authored elements in document order
 */
function collectNodes(block) {
  const out = [];
  block.querySelectorAll(':scope > div > div').forEach((cell) => {
    const kids = [...cell.children];
    if (kids.length) out.push(...kids);
    else if (cell.textContent.trim()) {
      // harness-only fallback (EW5)
      const p = document.createElement('p');
      p.append(...cell.childNodes);
      out.push(p);
    }
  });
  return out.length ? out : [...block.children];
}

/**
 * loads and decorates the block
 * @param {Element} block The block element
 */
export default async function decorate(block) {
  const nodes = collectNodes(block);
  if (!nodes.length) return;

  const heading = nodes.find((n) => n.matches('h1, h2, h3, h4'));
  const ctas = nodes.filter((n) => n.matches('p') && n.querySelector('a[href]'));
  const copy = nodes.filter((n) => n !== heading && !ctas.includes(n));

  const wrap = document.createElement('div');
  wrap.className = 'wrap';

  const mark = document.createElement('div');
  mark.className = 'closing-mark';
  mark.setAttribute('aria-hidden', 'true');
  mark.innerHTML = '<span class="closing-dot"></span>';
  wrap.append(mark);

  if (heading) {
    const headline = document.createElement('div');
    headline.className = 'headline';
    headline.append(heading);
    wrap.append(headline);
  }

  if (copy.length) {
    const body = document.createElement('div');
    body.className = 'closing-copy';
    copy.forEach((n) => body.append(n));
    wrap.append(body);
  }

  if (ctas.length) {
    const actions = document.createElement('div');
    actions.className = 'actions';
    ctas.forEach((p) => actions.append(p));
    wrap.append(actions);
  }

  const rule = document.createElement('div');
  rule.className = 'closing-rule';
  rule.setAttribute('aria-hidden', 'true');
  wrap.append(rule);

  block.replaceChildren(wrap);
}
